[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shared"
version = "0.1.0"
description = "Shared library for FL email spam detection pipeline"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26.0",
    "confluent-kafka==2.3.0",
]

[tool.setuptools.packages.find]
include = ["shared*"]
